[package]
name = "directory_filter"
version = "0.1.0"
authors = ["Seb Glazebrook <sebastian.glazebrook@redbubble.com>"]

[dependencies]
regex = "*"
crossbeam = "*"
time = "*"

[dependencies.directory_scanner]
git = "http://github.com/sebglazebrook/directory_scanner.git"
rev = "c19bc0d"
